name: Update README

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Update README with recent activity
        run: |
          echo "## :zap: Recent Activity" > README.md
          echo "<!--START_SECTION:activity-->" >> README.md
          echo "1. 💪 Opened PR [#3836](https://github.com/hoppscotch/hoppscotch/pull/3836) in [hoppscotch/hoppscotch](https://github.com/hoppscotch/hoppscotch)" >> README.md
          echo "2. 💪 Opened PR [#3835](https://github.com/hoppscotch/hoppscotch/pull/3835) in [hoppscotch/hoppscotch](https://github.com/hoppscotch/hoppscotch)" >> README.md
          echo "3. 💪 Opened PR [#3832](https://github.com/hoppscotch/hoppscotch/pull/3832) in [hoppscotch/hoppscotch](https://github.com/hoppscotch/hoppscotch)" >> README.md
          echo "4. 💪 Opened PR [#3829](https://github.com/hoppscotch/hoppscotch/pull/3829) in [hoppscotch/hoppscotch](https://github.com/hoppscotch/hoppscotch)" >> README.md
          echo "5. 🗣 Commented on [#3780](https://github.com/hoppscotch/hoppscotch/pull/3780#issuecomment-1934509627) in [hoppscotch/hoppscotch](https://github.com/hoppscotch/hoppscotch)" >> README.md
          echo "<!--END_SECTION:activity-->" >> README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with recent activity"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
